### PR TITLE
Fixes for clipping regions with multiple Y axes.  Also fixes inverted graphs with Axis.left specified.

### PR DESCRIPTION
**Pull request by sappling**
Please see http://jsfiddle.net/sappling/UGK5d/ for a demonstration of the general problem with clipping and multiple y Axes.
See http://jsfiddle.net/sappling/aFPcp/ for demonstration of the problem with an inverted graph with multiple y Axes.  Note that the inverted version doesn't just have a clipping problem, it doesn't honor the Axis.left option either.
I believe that this fix handles both of these issues.

This may need some more work in one area.  I was not exactly clear of the purpose of the sharedClipKey during animation.  I have not done anything similar for these new clip regions.  If you can help me understand this, I'll be glad to try to update the per-axis clipping regions similarly if needed.

### CODE REVIEW

**Comment by highslide-software** [comment]
This is fixed in Highstock: http://jsfiddle.net/highcharts/UGK5d/9/

Highcharts doesn't officially support yAxis.top and yAxis.height. http://api.highcharts.com/highcharts#yAxis.

**Comment by sebastianbochan** [comment]
When we refer to highcharts-more.js as well, then probelm still appears.
Example: http://jsfiddle.net/UGK5d/10/ and http://jsfiddle.net/L7k85drL/3/

**Comment by GreenRover** [comment]
Is this issue already fixed for highcharts-more.js? Or why do you closed this issue againe?

**Comment by sebastianbochan** [comment]
+1

**Comment by GreenRover** [comment]
Hello, can you please reopen that issue to fix highcharts-more.js to?

**Comment by highslide-software** [comment]
But it works doesn't it? http://jsfiddle.net/highcharts/UGK5d/11/

**Comment by GreenRover** [comment]
Yes in 2.1.6 it is fixed. In 2.1.5 it was not.
Thanks for fixing.

**Pull request closed without merging**
